language: node_js
if: (branch = master AND type = (pull_request OR cron)) OR (branch = develop)
node_js:
  # These are the recommended versions according to nodejs. We should make sure they all work.
  # - 8
  # - 9
  - 10
matrix:
  include:
    # Mac Installation. - It could easily be linux.
    - os: osx
      env:
        - PKG_MANAGER="npm"
        - HOMEBREW_NO_AUTO_UPDATE="1"
        - GLOBAL="$PKG_MANAGER install -g"
    - os: osx
      env:
        - PKG_MANAGER="yarn"
        - HOMEBREW_NO_AUTO_UPDATE="1"
        - GLOBAL="$PKG_MANAGER global add"
cache:
  yarn: true
  directories:
    - ${pwd}/frontend/node_modules
before_install:
  # If brew doesn't work, try the other one. We already specify a version of node, based on the build.
  - brew install yarn --without-node
  # - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  # - export PATH="$HOME/.yarn/bin:$PATH"
install:
  # Try to install all packages with both yarn and npm
  - cd frontend
  - $PKG_MANAGER install
before_script:
  # The GLOBAL env variable just helps introduce the differences in the commands to execute global installs of yarn or npm into our command.
  - $GLOBAL gulp-cli karma-cli
script:
  - gulp lint:js
  - gulp build
  - npm audit
  # - $PKG_MANAGER test
notifications:
  email: false
  slack:
    secure: maDjmvWUkdwQ3z3p2FFA0h2+UAHABVxmdmnGslxnRHEfPWvtLbkRODqT7M9CbF++0acdV6pBXwdJOPaD58mLeuxRglZlHATIiz0CPFGDO3l8b4zU0RxzFy+4L9FNp+fxR4HLfmPCcGP/cY8JfFEwbcFRPOt6I+iMYn5ugDTQweRaI/z9FNfYtfrqjPuUHCbM7sUuJMPueFDZwgygrsTSSWoK1K2tv+5s8qVetZOKcpLwukhCqFapCO/GUl5azly2DnfNdWiitB+9jL/T4NZRD0LsHxNzMfWM3ILCwcDU7IZof+AkQE/BWLlCNIyBHdt7HnJRRJ34S7iX3gIdAgDxizr7qE6pXJgH6vO3BpBdzNQ8qm1rnSL8P/oq844gvOU95YdgNIiAIYB7iDvisunofzJsuGkEJBTiuHzGlhK8y5po/hfXpEXp0g/3OSeqoEoUZVhHsS9fiOyeh75mgHVZ5gvJsSdV2eCdr5O/euvE9P0EG5c5vttVI9Ml/ayGZMcYJaT7UPNfwHhuidtuqYJVbx+CtIGI73GIqqgzYGgPcaA2LyHqbbXboGFlovRlEM4GhphkKdwP6TIssvnBZWpBFsnQM7ae3U9BnXOTfCuvCFYciPvII5E5A/hd9luLE8j+UGSp1CqpNFvp5nf6KekImZ78X8Y4IZ1PUDK+eMQ0yDM=
