# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 17:30
from __future__ import unicode_literals

import classifier.helpers.storage.media_file_system
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glyph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(max_length=128)),
                ('id_state_manual', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('ulx', models.PositiveIntegerField(blank=True, null=True)),
                ('uly', models.PositiveIntegerField(blank=True, null=True)),
                ('nrows', models.PositiveIntegerField(blank=True, null=True)),
                ('ncols', models.PositiveIntegerField(blank=True, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, storage=classifier.helpers.storage.media_file_system.MediaFileSystemStorage(), upload_to=classifier.helpers.storage.media_file_system.media_file_name)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='glyph',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classifier.Page'),
        ),
    ]
