# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0003_page_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlyphClass',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='glyph',
            name='glyph_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classifier.GlyphClass'),
        ),
    ]
