# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 19:06
from __future__ import unicode_literals

import classifier.helpers.storage.media_file_system
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0004_auto_20160407_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='glyph',
            name='context_thumbnail',
            field=models.ImageField(blank=True, null=True, storage=classifier.helpers.storage.media_file_system.MediaFileSystemStorage(), upload_to=classifier.helpers.storage.media_file_system.media_file_name),
        ),
    ]
