# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0005_glyph_context_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='binary_image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
