# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0006_page_binary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
