# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0007_auto_20160412_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glyph',
            name='context_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='glyph',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
