# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0008_auto_20160414_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameraClassifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='classifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classifier.GameraClassifier'),
        ),
    ]
