# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import neumeeditor.helpers.storage.media_file_system
import neumeeditor.models.fields.short_code_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glyph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', neumeeditor.models.fields.short_code_field.ShortCodeField(max_length=128)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, null=True, storage=neumeeditor.helpers.storage.media_file_system.MediaFileSystemStorage(), upload_to=neumeeditor.helpers.storage.media_file_system.media_file_name)),
                ('external_image', models.URLField(blank=True, null=True)),
                ('md5sum', models.CharField(blank=True, max_length=36, null=True)),
                ('folio_name', models.CharField(blank=True, max_length=64, null=True)),
                ('ulx', models.PositiveIntegerField(blank=True, null=True)),
                ('uly', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('glyph', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neumeeditor.Glyph')),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=128, unique=True)),
                ('glyph', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neumeeditor.Glyph')),
            ],
            options={
                'ordering': ['string'],
            },
        ),
        migrations.CreateModel(
            name='NameNomenclatureMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glyph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neumeeditor.Glyph')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neumeeditor.Name')),
            ],
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomenclature_name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'ordering': ['nomenclature_name'],
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='namenomenclaturemembership',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neumeeditor.Nomenclature'),
        ),
        migrations.AddField(
            model_name='name',
            name='nomenclatures',
            field=models.ManyToManyField(blank=True, null=True, through='neumeeditor.NameNomenclatureMembership', to='neumeeditor.Nomenclature'),
        ),
        migrations.AddField(
            model_name='glyph',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neumeeditor.Style'),
        ),
        migrations.AlterUniqueTogether(
            name='namenomenclaturemembership',
            unique_together=set([('name', 'nomenclature')]),
        ),
    ]
